import Header from "@/components/ui/header";
import "./globals.css";

export const metadata = {
	title: "Leelu v2",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
