export enum TypeformColumns {
  TIMESTAMP = "Timestamp",
  EMAIL = "Email",
  HER_FULL_NAME = "Her Full Name",
  HER_DOB = "Her DOB",
  TIER = "Tier",
  PATH = "Path",
  PARTNER_FULL_NAME = "His Full Name",
  PARTNER_DOB = "His DOB",
  PARTNER_DURATION = "Duration",
  REPORT_1_STATUS = "Report 1 Status",
  REPORT_2_STATUS = "Report 2 Status",
  REPORT_3_STATUS = "Report 3 Status",
  REPORT_4_STATUS = "Report 4 Status",
  NOTES = "Notes",
}
